server:
  port: 8081

spring:
  application:
    name: SUBSCRIPTION-SERVICE

  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    database: postgresql

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/KT_SUBSCRIPTION
    username: postgres
    password: root!

  kafka:
    bootstrap-servers: localhost:9092  # 또는 kafka:9092 (도커 내부에서는 kafka:9092일 수도 있음)
    consumer:
      group-id: subscription-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
    listener:
      ack-mode: record
