server:
  port: 8082

spring:
  application:
    name: SUBSCRIPTION-SERVICE

  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    database: postgresql

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/KT_PAYMENT
    username: postgres
    password: root!
