server:
  port: 8082

spring:

  config:
    import: optional:file:.env[.properties]

  application:
    name: PAYMENT-SERVICE

  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: payment-group
      auto-offset-reset: earliest

  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    database: postgresql

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/KT_PAYMENT
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}


toss:
  client-key: ${PAYMENT_CLIENT_KEY}
  secret-key: ${PAYMENT_SECRET_KEY}
