version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres151
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
